name: ci
on:
  push:
    branches:
    - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      #with:
      #  install: true
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: cache base builder
      uses: docker/build-push-action@v3
      with:
        push: True
        tags: ghcr.io/geoheil/containerfun-cache:latest
        #tags: ghcr.io/geoheil/containerfun:latest
        target: builder
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: fooasdf
      run: docker buildx build --cache-from type=gha --target app --tag ghcr.io/geoheil/containerfun-app:latest
      
    - name: foo
      run: docker run ghcr.io/geoheil/containerfun-app:latest ls /

    - name: fook
      run: docker run ghcr.io/geoheil/containerfun-app:latest cat /asdf.txt
